name: Node js app deploy to EKS
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install kubectl
      uses: azure/setup-kubectl@v2.0
      with:
        version: 'v1.24.0' # default is latest stable
      id: install

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: AKIAQ3EGWGMKDDLTQJFN
        aws-secret-access-key: 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
        aws-region: us-east-1

    # - name: Update kube config
    #   run: aws eks update-kubeconfig --name <clustername>

    # - name: Deploy to EKS
    #   run: |
    #     kubectl apply -f deployment.yaml
    #     kubectl apply -f service.yaml
